export const UPDATE_USER = "UPDATE_USER"

export const UPDATE_STREAMDATA = "UPDATE_STREAMDATA"

export const UPDATE_CLIENT_STREAM_OUT = "UPDATE_CLIENT_STREAM_OUT"

export const SELECT_COMPONENT = "SELECT_COMPONENT"
export const DESELECT_COMPONENT = "DESELECT_COMPONENT"
export const DESELECT_ALL = "DESELECT_ALL"

export const ADD_DATA_POINT = "ADD_DATA_POINT"
export const SET_GRAPH_DATA = "SET_GRAPH_DATA"

export const SET_BATCHES = "SET_BATCHES"
export const ADD_BATCH_DATA_POINT = "ADD_DATA_POINT"
export const SET_BATCH_DATA = "SET_GRAPH_DATA"