export const UPDATE_USER = "UPDATE_USER"

export const UPDATE_STREAMDATA = "UPDATE_STREAMDATA"

export const UPDATE_CLIENT_STREAM_OUT = "UPDATE_CLIENT_STREAM_OUT"

export const SELECT_COMPONENT = "SELECT_COMPONENT"
export const DESELECT_COMPONENT = "DESELECT_COMPONENT"